Allow to pass env vars for local preview
spacelift-io/spacectl pull request #145
Opened 2023-05-12 10:53 UTC by tomasmik

2023-05-12 10:53 UTC, Clickup-user commented
Task linked: [CU-862j7j7mq Add --tf-env-var/--env-var flags to spacectl stack local-preview](https://app.clickup.com/t/862j7j7mq)

2023-05-22 09:11 UTC, Yantrio requested changes

2023-05-22 09:11 UTC, Yantrio commented on internal/cmd/stack/flags.go
> +	Usage: "[Optional] Environment variables injected into the run at runtime, example: --tf-env-var 'foo=bar,bar=baz'",
the example should use `--env-var` here
```suggestion
	Usage: "[Optional] Environment variables injected into the run at runtime, example: --env-var 'foo=bar,bar=baz'",
```

2023-05-22 09:11 UTC, Yantrio commented on main.go
> +		EnableBashCompletion: true,
Nice addition

2023-05-22 09:26 UTC, Yantrio approved these changes

2023-05-23 10:12 UTC, cube2222 commented on internal/cmd/stack/flags.go
> +}
Maybe we could call them --tf-env-var-override and --env-var-override, respectively, to emphasise the overriding part?

2023-05-23 10:13 UTC, cube2222 commented on internal/cmd/stack/local_preview.go
> +	if !cliCtx.IsSet(flagEnvVars.Name) && !cliCtx.IsSet(flagEnvVarsTF.Name) {
Don't think this early return is necessary, no? It'll just iterate over two empty lists.

2023-05-23 10:14 UTC, cube2222 approved these changes

2023-05-23 11:09 UTC, merged